export const Pieces = [
    { id: 0, name: 'rook', color: 0 },
    { id: 1, name: 'knight', color: 0 },
    { id: 2, name: 'bishop', color: 0 },
    { id: 3, name: 'queen', color: 0 },
    { id: 4, name: 'king', color: 0 },
    { id: 5, name: 'bishop', color: 0 },
    { id: 6, name: 'knight', color: 0 },
    { id: 7, name: 'rook', color: 0 },
    { id: 8, name: 'pawn', color: 0 },
    { id: 9, name: 'pawn', color: 0 },
    { id: 10, name: 'pawn', color: 0 },
    { id: 11, name: 'pawn', color: 0 },
    { id: 12, name: 'pawn', color: 0 },
    { id: 13, name: 'pawn', color: 0 },
    { id: 14, name: 'pawn', color: 0 },
    { id: 15, name: 'pawn', color: 0 },
    
    { id: 16, name: 'rook', color: 1 },
    { id: 17, name: 'knight', color: 1 },
    { id: 18, name: 'bishop', color: 1 },
    { id: 19, name: 'queen', color: 1 },
    { id: 20, name: 'king', color: 1 },
    { id: 21, name: 'bishop', color: 1 },
    { id: 22, name: 'knight', color: 1 },
    { id: 23, name: 'rook', color: 1 },
    { id: 24, name: 'pawn', color: 1 },
    { id: 25, name: 'pawn', color: 1 },
    { id: 26, name: 'pawn', color: 1 },
    { id: 27, name: 'pawn', color: 1 },
    { id: 28, name: 'pawn', color: 1 },
    { id: 29, name: 'pawn', color: 1 },
    { id: 30, name: 'pawn', color: 1 },
    { id: 31, name: 'pawn', color: 1 },
];